/**
 * Socket event name constants.
 * Single source of truth for all event names used between client and server.
 */

// CLIENT → SERVER
const CLIENT_EVENTS = {
    CREATE_ROOM: 'CREATE_ROOM',
    JOIN_ROOM: 'JOIN_ROOM',
    PLAY_VIDEO: 'PLAY_VIDEO',
    PAUSE_VIDEO: 'PAUSE_VIDEO',
    SEEK_VIDEO: 'SEEK_VIDEO',
    PING: 'PING',
    REQUEST_SYNC: 'REQUEST_SYNC',
    LEAVE_ROOM: 'LEAVE_ROOM',
    TERMINATE_SESSION: 'TERMINATE_SESSION',
    // File transfer (broadcaster → server → listeners)
    FILE_START: 'FILE_START',
    FILE_CHUNK: 'FILE_CHUNK',
    FILE_END: 'FILE_END',
    REQUEST_FILE: 'REQUEST_FILE',
    // WebRTC signaling (camera mode)
    WEBRTC_OFFER: 'WEBRTC_OFFER',
    WEBRTC_ANSWER: 'WEBRTC_ANSWER',
    WEBRTC_ICE_CANDIDATE: 'WEBRTC_ICE_CANDIDATE',
    WEBRTC_READY: 'WEBRTC_READY',
};

// SERVER → CLIENT
const SERVER_EVENTS = {
    ROOM_CREATED: 'ROOM_CREATED',
    ROOM_JOINED: 'ROOM_JOINED',
    ROOM_JOIN_ERROR: 'ROOM_JOIN_ERROR',
    SYNC_STATE: 'SYNC_STATE',
    VIDEO_PLAY: 'VIDEO_PLAY',
    VIDEO_PAUSE: 'VIDEO_PAUSE',
    VIDEO_SEEK: 'VIDEO_SEEK',
    SYNC_TICK: 'SYNC_TICK',
    PONG: 'PONG',
    LATENCY_UPDATE: 'LATENCY_UPDATE',
    USER_COUNT_UPDATE: 'USER_COUNT_UPDATE',
    SIGNAL_STRENGTH_UPDATE: 'SIGNAL_STRENGTH_UPDATE',
    BROADCAST_ENDED: 'BROADCAST_ENDED',
    SESSION_TERMINATED: 'SESSION_TERMINATED',
    SYNC_WARNING: 'SYNC_WARNING',
    // File transfer
    FILE_START: 'FILE_START',
    FILE_CHUNK: 'FILE_CHUNK',
    FILE_END: 'FILE_END',
    FILE_PROGRESS: 'FILE_PROGRESS',
    // WebRTC signaling
    WEBRTC_OFFER: 'WEBRTC_OFFER',
    WEBRTC_ANSWER: 'WEBRTC_ANSWER',
    WEBRTC_ICE_CANDIDATE: 'WEBRTC_ICE_CANDIDATE',
    WEBRTC_READY: 'WEBRTC_READY',
};

module.exports = { CLIENT_EVENTS, SERVER_EVENTS };
